name = "ext-auth"
account_id = "<fill in>"
workers_dev = true
compatibility_date = "2024-04-19"
main = "index.ts"

kv_namespaces = [
  { binding = "KV", id = "<fill in>", preview_id = "<fill in>" },
]

[vars]
TEAM_DOMAIN="<update>.cloudflareaccess.com"
